### ISSUE TITLE
FR7 - Generate a basic financial report

### ISSUE THREAD

**Issue by Jasminezhang1** [WSU-4110/4110FinanceAnalyzer#10]
|FR7 - Generate a basic financial report|
|---|
|**Goal**: The goal is to provide user a function to generate a financial report
**Stakeholders:** Users|
| **Description:** When an user select generate report, the app shall be able to generate a basic financial report that includes the following key elemnets: income, expenses, pi chart, categorization of the fiance |
| **Origin:** This requirement is based on the initial scope of the product vision.|
| **Version:** 1.0  |  
|**Date:** 03/02/24 
|  **Priority:** 1 |

**Comment by devbarr28** [comment]
A simple financial report is displayed on the home page showing different categories of income, spending and bills due.
