### ISSUE TITLE
FR8 User can set data category

### ISSUE THREAD

**Issue by Jasminezhang1** [WSU-4110/4110FinanceAnalyzer#11]
|FR8 User can set data category|
|---|
|**Goal**: The goal is to provide user a function to categorize the data
**Stakeholders:** Users|
| **Description:** When an user load in a set of data, the app shall be able to provide a way to the users to categorize the data |
| **Origin:** This requirement is based on the initial scope of the product vision.|
| **Version:** 1.0  |  
|**Date:** 03/02/24 
|  **Priority:** 1 |

**Comment by devbarr28** [comment]
There is a category tab inside the bill page allowing for user to specify what type of category their bills falls under.
