### ISSUE TITLE
FR10 - The user can pick a date when entering data

### ISSUE THREAD

**Issue by Jasminezhang1** [WSU-4110/4110FinanceAnalyzer#12]
|FR8 The user can pick a date when entering data|
|---|
|**Goal**: The goal is to provide user a function to date the data
**Stakeholders:** Users|
| **Description:** When an user load in a set of data, the app shall be able to provide a way to the users to date the data |
| **Origin:** This requirement is based on the initial scope of the product vision.|
| **Version:** 1.0  |  
|**Date:** 03/02/24 
|  **Priority:** 1 |

**Comment by devbarr28** [comment]
When picking bill due dates a calendar  pops up letting you choose a date of your choice.
