### ISSUE TITLE
NFR4 The user interface should be intuitive and user-friendly

### ISSUE THREAD

**Issue by Jasminezhang1** [WSU-4110/4110FinanceAnalyzer#13]
|NFR4 The user interface should be intuitive and user-friendly|
|---|
|**Goal**: The goal is to provide user an intuitive and user-friendly interface
**Stakeholders:** Users|
| **Description:** When an user is presented with a user interface, they shall be able to understand what needs to be done next |
| **Origin:** This requirement is based on the initial scope of the product vision.|
| **Version:** 1.0  |  
|**Date:** 03/02/24 
|  **Priority:** 1 |

**Comment by devbarr28** [comment]
Easy to use and navigate with simple features.
