### ISSUE TITLE
FR14 Notifications

### ISSUE THREAD

**Issue by khaledsaif18** [WSU-4110/4110FinanceAnalyzer#17]
|FR14 Notifications|
|---|
|**Goal**: Provides notifications for upcoming bills or financial milestones. |
**Stakeholders:** Users|
| **Description:** The application will notify the user of any upcoming bills or financial milestones they have reached. The user will have the option of turning those notifications on or off. |
| **Origin:** This requirement is based on the initial scope of the product vision.|
| **Version:** 1.0  |  
|**Date:** 02/03/24 |
|  **Priority:** 1 |

**Comment by devbarr28** [comment]
added a tab to turn on and off notifications
