### ISSUE TITLE
FR2. Calculate Totals and Spending Daily

### ISSUE THREAD

**Issue by KerryZ1215** [WSU-4110/4110FinanceAnalyzer#2]
|FR2.  Calculate Totals and Spending Daily|
|---|
|**Goal**: The system will calculate daily totals and spending for users, providing them with an overview of their daily financial activities.
**Stakeholders:** Users|
| **Description:** This feature enables the finance analyzer application to calculate and display daily totals and spending for each user based on their recorded financial transactions. Users will have access to a daily summary including total income, expenses, and net spending. This information will assist users in monitoring their daily financial health and making informed decisions. |
| **Origin:** This requirement is identified to provide users with a daily overview of their financial activities within the app.|
| **Version:** 1.0  |  
|**Date:** 03/02/2024 
|  **Priority:** 2 |

**Comment by devbarr28** [comment]
One our home page it shows income and other daily charges with upcoming bills
