### ISSUE TITLE
FR3.  User Data Entry

### ISSUE THREAD

**Issue by KerryZ1215** [WSU-4110/4110FinanceAnalyzer#3]
|FR3.  User Data Entry|
|---|
|**Goal**: The system will allow users to manually enter and record their financial data into the application, including income and expenses.
**Stakeholders:** Users|
| **Description:** This feature lets users input their financial transactions and details directly into the finance analyzer application. Users can specify transaction type (income or expense), date, amount, category, and additional notes. The entered data will be used for the application's calculations, analysis, and financial reporting. |
| **Origin:** This requirement is identified to provide users with the ability to input and track their financial transactions within the app.|
| **Version:** 1.0  |  
|**Date:** 03/02/2024 
|  **Priority:** 1 |

**Comment by devbarr28** [comment]
Users can enter data for login/signup, add bills they have upcoming with name date amount and category.
