### ISSUE TITLE
FR4.  Data Storage to Database

### ISSUE THREAD

**Issue by KerryZ1215** [WSU-4110/4110FinanceAnalyzer#4]
|FR4.  Data Storage to Database|
|---|
|**Goal**: The system will securely store user-generated financial data in a database to ensure data persistence and accessibility.
**Stakeholders:** System Administrators|
| **Description:** This functionality allows the finance analyzer application to store user-entered financial data in a database, including transactions, income, expenses, and user profiles. The data will be organized, indexed, and maintained to ensure efficient retrieval and processing for various app functionalities, such as calculations, reporting, and analysis. The database will be designed to handle the growing volume of user data as the user base expands. |
| **Origin:** This requirement is identified to ensure that user-generated financial data is retained securely and can be retrieved when needed for analysis and reporting.|
| **Version:** 1.0  |  
|**Date:** 09/11/2019  
|  **Priority:** 1 |

**Comment by devbarr28** [comment]
Stores data in our phpMyAdmin database.
